const edital = [
    { id: 'financas-publicas', nome: 'Finanças Públicas', peso: null, assuntos: [
        { id: 'lei-4320', nome: 'Lei nº 4.320/1964', subtopicos: ['Princípios', 'Receita', 'Despesa', 'Classificações', 'Estágios', 'Créditos adicionais', 'Restos a pagar', 'Despesas de exercícios anteriores', 'Fontes e destinações'] },
        { id: 'lrf', nome: 'Lei de Responsabilidade Fiscal', subtopicos: ['Princípios', 'Receita corrente líquida', 'Despesa com pessoal', 'Limites', 'Dívida pública', 'Renúncia de receita'] },
        { id: 'ppa-ldo-loa', nome: 'PPA/LDO/LOA', subtopicos: ['Princípios', 'Receita', 'Despesa', 'Classificações', 'Estágios', 'Créditos adicionais', 'Restos a pagar', 'Despesas de exercícios anteriores', 'Fontes e destinações'] }
    ] },
    { id: 'governanca-ti', nome: 'Governança, Gestão de TI e Projetos', peso: null, assuntos: [
        { id: 'governanca-gestao', nome: 'Governança e gestão de TI', subtopicos: ['Alinhamento estratégico', 'Serviços', 'Processos', 'Riscos', 'Controles', 'Indicadores', 'SLAs'] },
        { id: 'cobit-itil', nome: 'COBIT 2019 e ITIL v5', subtopicos: ['Princípios', 'Governança', 'Gestão de serviços', 'Processos', 'Práticas'] },
        { id: 'contratos-ti', nome: 'Contratação e gestão de bens e serviços de TI', subtopicos: ['Governança de contratos', 'Fornecedores', 'Indicadores', 'Níveis mínimos de serviço', 'SLA', 'Aceite', 'Entregáveis', 'Qualidade', 'Produtividade', 'Desempenho', 'Riscos', 'Controles', 'Monitoramento', 'Conformidade', 'Resultados'] },
        { id: 'pmbok-agil', nome: 'PMBOK 8ª edição e métodos ágeis', subtopicos: ['Planejamento', 'Execução', 'Riscos', 'Métodos preditivos', 'Métodos adaptativos', 'Métodos híbridos', 'Scrum Guide 2020', 'Kanban'] }
    ] },
    { id: 'engenharia-software', nome: 'Engenharia e Arquitetura de Software', peso: null, assuntos: [
        { id: 'processos-arquitetura', nome: 'Processos e arquitetura', subtopicos: ['Ciclo de vida', 'Processos de software', 'Engenharia de requisitos', 'Requisitos funcionais', 'Requisitos não funcionais', 'Arquitetura', 'Arquiteturas distribuídas', 'Microsserviços', 'Integração'] },
        { id: 'qualidade-metricas', nome: 'Qualidade, testes e métricas', subtopicos: ['Qualidade', 'Testes', 'Métricas de software', 'Métricas funcionais', 'Métricas não funcionais', 'Análise de Pontos de Função', 'Use Case Points', 'Produtividade', 'Esforço', 'Cronograma', 'Custo', 'Manutenibilidade', 'Complexidade', 'Estimativas', 'Medição', 'Aceite', 'Faturamento', 'Fiscalização'] },
        { id: 'desenvolvimento-web', nome: 'Desenvolvimento e integração', subtopicos: ['Git 2.x', 'CI/CD', 'DevOps', 'DevSecOps', 'REST', 'HTTP', 'HTTPS', 'JSON', 'XML', 'Autenticação', 'Autorização', 'Mensageria', 'Interoperabilidade', 'Web', 'C#', '.NET', 'ASP.NET', 'HTML5', 'CSS3', 'JavaScript', 'TypeScript', 'Programação orientada a objetos', 'Arquitetura em camadas', 'Cliente-servidor', 'Leitura de código'] }
    ] },
    { id: 'integracao-publica', nome: 'Sistemas de Integração / Administração Pública', peso: null, assuntos: [{ id: 'sistemas-publicos', nome: 'Sistemas estruturados e integrações', subtopicos: ['Planejamento', 'Orçamento', 'Finanças', 'Contabilidade', 'Compras', 'Licitações', 'Contratos', 'Patrimônio', 'APIs', 'Web services', 'Barramentos', 'Mensageria', 'Interoperabilidade', 'Segurança', 'Qualidade', 'Consistência', 'Rastreabilidade', 'Integrações', 'Controles'] }] },
    { id: 'banco-dados', nome: 'Banco de Dados e SQL', peso: null, assuntos: [
        { id: 'modelagem', nome: 'Modelagem e administração', subtopicos: ['Modelagem conceitual', 'Modelagem lógica', 'Modelagem física', 'MER', 'Modelo relacional', 'Entidades', 'Relacionamentos', 'Chaves', 'Integridade', 'Normalização', 'Transações', 'Concorrência', 'Índices', 'Particionamento', 'Views', 'Segurança', 'Backup', 'Recuperação', 'Bancos relacionais', 'NoSQL'] },
        { id: 'bancos-versoes', nome: 'SGBDs', subtopicos: ['PostgreSQL 18', 'MySQL 8.4 LTS', 'SQL Server 2025', 'MongoDB 8.0 ou superior'] },
        { id: 'sql', nome: 'SQL e otimização', subtopicos: ['DDL', 'DML', 'DCL', 'TCL', 'Filtros', 'Agrupamentos', 'Joins', 'Subqueries', 'CTE', 'Operações de conjunto', 'Window Functions', 'Views', 'Transações', 'Índices', 'Planos de execução', 'Otimização'] }
    ] },
    { id: 'data-engineering', nome: 'Data Warehouse / Data Engineering', peso: null, assuntos: [{ id: 'plataformas-dados', nome: 'Plataformas e processamento de dados', subtopicos: ['Data Warehouse', 'Data Mart', 'Data Lake', 'Lakehouse', 'OLTP', 'OLAP', 'Modelagem dimensional', 'Fatos', 'Dimensões', 'Star Schema', 'Snowflake Schema', 'ETL', 'ELT', 'Coleta', 'Ingestão', 'Limpeza', 'Transformação', 'Integração', 'Armazenamento', 'Batch', 'Streaming', 'Processamento distribuído', 'Big Data', 'Arquiteturas escaláveis', 'Spark 4.x', 'DataFrame', 'Spark SQL'] }] },
    { id: 'governanca-dados', nome: 'Governança e Qualidade de Dados', peso: null, assuntos: [{ id: 'qualidade-dados', nome: 'Governança e qualidade', subtopicos: ['Papéis', 'Catálogo', 'Glossário', 'Metadados', 'Dicionário', 'Linhagem', 'Ciclo de vida', 'Dados mestres', 'Dados de referência', 'Completude', 'Consistência', 'Validade', 'Exatidão', 'Unicidade', 'Integridade', 'Atualidade', 'Profiling', 'Limpeza', 'Inconsistências', 'Duplicidades', 'Dados ausentes', 'Outliers'] }] },
    { id: 'bi-analytics', nome: 'BI / Analytics / Visualização', peso: null, assuntos: [{ id: 'bi-powerbi', nome: 'BI e Power BI', subtopicos: ['Arquitetura de BI', 'Indicadores', 'Métricas', 'Relatórios', 'Dashboards', 'Análise descritiva', 'Análise diagnóstica', 'Análise preditiva', 'Análise prescritiva', 'Self-service BI', 'Visualização de dados', 'Comunicação de dados', 'Power BI atual', 'Power Query', 'M', 'Modelagem', 'DAX', 'Medidas', 'Relacionamentos', 'Filtros'] }] },
    { id: 'programacao-dados', nome: 'Programação e Automação para Dados', peso: null, assuntos: [{ id: 'python-automacao', nome: 'Programação, dados e automação', subtopicos: ['Lógica', 'Algoritmos', 'Estruturas de dados', 'Funções', 'Arquivos', 'Exceções', 'Python 3.14.x', 'NumPy 2.5.x', 'pandas 3.0.x', 'Manipulação de dados', 'Transformação', 'Integração', 'Análise', 'CSV', 'JSON', 'XML', 'APIs', 'Web scraping', 'Automação', 'RPA'] }] },
    { id: 'data-science', nome: 'Estatística / Data Science / Machine Learning', peso: null, assuntos: [{ id: 'estatistica-ml', nome: 'Estatística e aprendizado de máquina', subtopicos: ['Estatística descritiva', 'Estatística inferencial', 'Medidas de posição', 'Medidas de dispersão', 'Probabilidade', 'Distribuições', 'Amostragem', 'Correlação', 'Regressão', 'Intervalos de confiança', 'Testes de hipóteses', 'EDA', 'Ciclo de vida de Data Science', 'Preparação de features', 'Feature engineering', 'Seleção de features', 'Aprendizado supervisionado', 'Aprendizado não supervisionado', 'Classificação', 'Regressão', 'Clustering', 'Árvores de decisão', 'Ensembles', 'Métodos baseados em distância', 'Treinamento', 'Validação', 'Overfitting', 'Underfitting', 'Métricas de avaliação', 'scikit-learn 1.9.x'] }] },
    { id: 'anomalias', nome: 'Anomalias / Padrões Suspeitos', peso: null, assuntos: [{ id: 'deteccao-risco', nome: 'Detecção de anomalias e risco', subtopicos: ['Métodos estatísticos', 'Regras', 'Machine Learning', 'Anomalias', 'Outliers', 'Padrões suspeitos', 'Finanças', 'Orçamento', 'Contabilidade', 'Compras', 'Contratos', 'Licitações', 'Inconsistências', 'Duplicidades', 'Fracionamento', 'Concentração', 'Relacionamentos atípicos', 'Falsos positivos', 'Falsos negativos', 'Indicadores de risco', 'Priorização de casos'] }] },
    { id: 'ia-nlp', nome: 'IA / NLP / IA Generativa', peso: null, assuntos: [{ id: 'ia-generativa', nome: 'Inteligência artificial e NLP', subtopicos: ['Inteligência Artificial', 'Deep Learning', 'Redes neurais', 'NLP', 'Classificação', 'Extração de informação', 'Entidades', 'Similaridade', 'Busca semântica', 'Sumarização', 'LLMs', 'Transformers', 'Tokens', 'Embeddings', 'Contexto', 'Prompt Engineering', 'RAG', 'Vector Databases', 'Agentes', 'Multimodalidade', 'PyTorch', 'TensorFlow', 'Alucinações', 'Viés', 'Segurança', 'Privacidade', 'Explicabilidade', 'Supervisão humana', 'IA responsável'] }] },
    { id: 'infra-cloud', nome: 'Infraestrutura / Redes / Cloud', peso: null, assuntos: [{ id: 'redes-cloud', nome: 'Infraestrutura, redes e nuvem', subtopicos: ['Servidores', 'Sistemas operacionais', 'Virtualização', 'Storage', 'Containers', 'Alta disponibilidade', 'Load balancing', 'OSI', 'TCP/IP', 'IPv4', 'IPv6', 'TCP', 'UDP', 'DNS', 'DHCP', 'HTTP', 'HTTPS', 'LAN', 'WAN', 'WLAN', 'VLAN', 'NAT', 'VPN', 'Roteamento', 'Switching', 'IaaS', 'PaaS', 'SaaS', 'Cloud público', 'Cloud privado', 'Cloud híbrido', 'Elasticidade', 'Escalabilidade', 'Serviços gerenciados', 'Banco de dados', 'Serverless', 'Monitoramento', 'Backup', 'Responsabilidade compartilhada', 'AWS', 'Azure', 'GCP', 'Docker', 'Kubernetes'] }] },
    { id: 'seguranca', nome: 'Segurança / Privacidade', peso: null, assuntos: [{ id: 'seguranca-lgpd', nome: 'Segurança da informação e LGPD', subtopicos: ['Confidencialidade', 'Integridade', 'Disponibilidade', 'Autenticidade', 'Não repúdio', 'Ameaças', 'Vulnerabilidades', 'Riscos', 'Controles', 'IAM', 'MFA', 'RBAC', 'Redes', 'Sistemas', 'Bancos', 'APIs', 'Aplicações', 'Endpoints', 'Pipelines', 'Cloud', 'Firewalls', 'IDS', 'IPS', 'WAF', 'Hardening', 'Patches', 'Logs', 'Monitoramento', 'Incidentes', 'Backup', 'Continuidade', 'Criptografia simétrica', 'Criptografia assimétrica', 'Hashes', 'Certificados', 'Assinaturas digitais', 'PKI', 'TLS', 'Chaves', 'Secrets', 'LGPD', 'Privacy by Design', 'Minimização', 'Anonimização', 'Pseudonimização', 'Mascaramento', 'Dados em repouso', 'Dados em trânsito'] }] },
    { id: 'auditoria-ti', nome: 'Auditoria / Controle com Tecnologia', peso: null, assuntos: [{ id: 'auditoria-tecnologia', nome: 'Auditoria de dados, contratos e sistemas', subtopicos: ['Bancos de dados', 'SQL', 'BI', 'Data science', 'Automação', 'IA', 'Extração', 'Integração', 'Cruzamento', 'Análise', 'Testes automatizados', 'Inconsistências', 'Exceções', 'Anomalias', 'Padrões suspeitos', 'Indicadores de risco', 'Relatórios', 'Dashboards', 'Dados financeiros', 'Dados orçamentários', 'Receitas', 'Despesas', 'Compras', 'Contratos', 'Licitações', 'Rastreabilidade', 'Integridade', 'Reprodutibilidade', 'Documentação', 'Auditoria de contratos de TI', 'Conformidade', 'SLA', 'Indicadores', 'Métricas de software', 'Produtividade', 'Qualidade', 'Aceite', 'Medições', 'Faturamento', 'Desempenho de fornecedores', 'Requisitos', 'Arquitetura', 'Código-fonte', 'Integrações', 'Controles', 'Trilhas de auditoria', 'Conformidade com especificações'] }] },
    { id: 'ingles-tecnico', nome: 'Inglês Técnico', peso: null, assuntos: [{ id: 'technical-english', nome: 'Technical English', subtopicos: ['Leitura técnica', 'Vocabulário de tecnologia', 'Interpretação de textos', 'Documentação técnica'] }] },
    { id: 'conhecimentos-gerais', nome: 'Conhecimentos Gerais', peso: null, assuntos: [
        { id: 'lingua-portuguesa', nome: 'Língua Portuguesa', subtopicos: ['Interpretação de textos', 'Tipologia e gêneros textuais', 'Coesão e coerência', 'Ortografia oficial', 'Acentuação gráfica', 'Classes de palavras', 'Formação de palavras', 'Sintaxe da oração e do período', 'Concordância verbal e nominal', 'Regência verbal e nominal', 'Crase', 'Colocação pronominal', 'Pontuação', 'Semântica', 'Redação oficial'] },
        { id: 'raciocinio-logico', nome: 'Raciocínio lógico e matemático', subtopicos: ['Proposições e conectivos', 'Tabelas-verdade', 'Equivalências e negações', 'Argumentação lógica', 'Conjuntos', 'Análise combinatória', 'Probabilidade', 'Porcentagem', 'Razão e proporção', 'Regra de três', 'Equações', 'Sequências', 'Estatística básica', 'Leitura de tabelas e gráficos'] },
        { id: 'atualidades-cidadania', nome: 'Atualidades, cidadania e administração pública', subtopicos: ['Organização político-administrativa brasileira', 'Cidadania e direitos fundamentais', 'Políticas públicas', 'Ética no serviço público', 'Transparência e controle social', 'Desenvolvimento sustentável', 'Economia brasileira e catarinense', 'Atualidades nacionais e internacionais'] }
    ] },
    { id: 'direito-publico', nome: 'Direito Público', peso: null, assuntos: [
        { id: 'constitucional', nome: 'Direito Constitucional', subtopicos: ['Princípios fundamentais', 'Direitos e garantias fundamentais', 'Remédios constitucionais', 'Organização do Estado', 'Administração pública na Constituição', 'Poder Legislativo', 'Poder Executivo', 'Poder Judiciário', 'Funções essenciais à Justiça', 'Controle de constitucionalidade', 'Ordem econômica e financeira', 'Ordem social'] },
        { id: 'administrativo', nome: 'Direito Administrativo', subtopicos: ['Princípios administrativos', 'Organização administrativa', 'Agentes públicos', 'Poderes administrativos', 'Atos administrativos', 'Serviços públicos', 'Licitações e contratos', 'Responsabilidade civil do Estado', 'Bens públicos', 'Intervenção do Estado na propriedade', 'Processo administrativo', 'Improbidade administrativa', 'Controle da administração pública'] },
        { id: 'tributario', nome: 'Direito Tributário', subtopicos: ['Sistema tributário nacional', 'Competência tributária', 'Limitações ao poder de tributar', 'Tributos e espécies tributárias', 'Obrigação tributária', 'Crédito tributário', 'Lançamento', 'Suspensão, extinção e exclusão do crédito', 'Administração tributária', 'Impostos estaduais', 'ICMS', 'IPVA', 'ITCMD'] },
        { id: 'penal', nome: 'Direito Penal', subtopicos: ['Aplicação da lei penal', 'Teoria do crime', 'Culpabilidade', 'Concurso de pessoas', 'Penas', 'Extinção da punibilidade', 'Crimes contra a administração pública', 'Crimes contra o patrimônio', 'Crimes contra a fé pública', 'Legislação penal especial'] }
    ] },
    { id: 'direito-privado', nome: 'Direito Privado', peso: null, assuntos: [
        { id: 'civil-parte-geral', nome: 'Direito Civil: parte geral', subtopicos: ['Pessoas naturais e jurídicas', 'Domicílio', 'Bens', 'Fatos jurídicos', 'Negócio jurídico', 'Prescrição e decadência', 'Provas'] },
        { id: 'civil-obrigacoes', nome: 'Direito Civil: obrigações, contratos e responsabilidade', subtopicos: ['Modalidades das obrigações', 'Transmissão das obrigações', 'Adimplemento e inadimplemento', 'Contratos em geral', 'Contratos em espécie', 'Responsabilidade civil', 'Posse e propriedade', 'Direito de família', 'Sucessões'] },
        { id: 'empresarial', nome: 'Direito Empresarial', subtopicos: ['Empresário e empresa', 'Sociedades empresárias', 'Estabelecimento empresarial', 'Títulos de crédito', 'Recuperação judicial e falência', 'Propriedade industrial'] },
        { id: 'consumidor', nome: 'Direito do Consumidor', subtopicos: ['Relação de consumo', 'Direitos básicos do consumidor', 'Responsabilidade pelo fato e vício', 'Práticas comerciais', 'Proteção contratual', 'Defesa do consumidor'] },
        { id: 'processo-civil', nome: 'Processo Civil', subtopicos: ['Normas processuais', 'Jurisdição e ação', 'Partes e procuradores', 'Atos processuais', 'Tutela provisória', 'Formação, suspensão e extinção do processo', 'Procedimento comum', 'Provas', 'Sentença e coisa julgada', 'Cumprimento de sentença', 'Execução', 'Recursos'] }
    ] }
];
window.edital = edital;